### ISSUE TITLE
The balloon policy can't adjust CPU frequency

### ISSUE THREAD

**Issue by changzhi1990** [containers/nri-plugins#57]
I use the below configmap:
```
apiVersion: v1
data:
  nri-resource-policy.cfg: |
    policy:
      Active: balloons
      ReservedResources:
        CPU: 750m
      AvailableResources:
        CPU: cpuset:0-27,56-83
      balloons:
        BalloonTypes:
          - Name: "b0"
            MinCpus: 4
            MaxCPUs: 4
            CPUClass: low
            MinBalloons: 2
    cpu:
      classes:
        default:
          minFreq: 1600000
          maxFreq: 1600000
        high:
          minFreq: 3000000
          maxFreq: 3000000
        low:
          minFreq: 1000000
          maxFreq: 1000000
        turbo:
          minFreq: 3000000
          maxFreq: 3600000
    logger:
      Debug: resource-manager,cache,policy,resource-control
    instrumentation:
      HTTPEndpoint: :8891
      PrometheusExport: true
kind: ConfigMap
metadata:
  name: nri-resource-policy-config
  namespace: kube-system
```

After creating the balloon policy deployment, I can see the balloons are created successfully:
![image](https://github.com/containers/nri-plugins/assets/12726668/3fd94e52-f2c5-4224-bf5b-3df1e889450b)

But the CPU frequency of them doesn't be adjusted:
![image](https://github.com/containers/nri-plugins/assets/12726668/deaffc2f-4b5b-4145-b7ce-a291e9b16fdd)

The CPU frequency should be adjusted to 1GHz as the configmap showed.

Further more, I try to create a nginx pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    balloon.balloons.resource-policy.nri.io: b0
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "4"
        memory: "100M"
      limits:
        cpu: "4"
        memory: "100M"
```
Also, the CPU frequency doesn't be adjusted. And the log of the NRI pod:

![image](https://github.com/containers/nri-plugins/assets/12726668/7a50d535-3b30-491e-8d32-c644d8f60ec8)

I have tested the CRI-RM balloon policy on the same machine. The CPU frequency can be adjusted correctly. So I suppose that maybe this is a bug in the NRI balloon policy.

**Comment by marquiz** [comment]
Any insight @askervin @jukkar ?

**Comment by kunshen1** [comment]
Is there any pre-request for deploying nri-balloon policy? 
Such as:
**OS** - Ubuntu/CentOS
**CPU driver** - intel_cpuacpi / intel_pstat
**Governor** - performance/powersave/...
**EPB** - performance/normal/...
**Intel_uncore_frequency driver** - enable/disable

Hope you guys can provide some suggestions?

**Comment by changzhi1990** [comment]
> Is there any pre-request for deploying nri-balloon policy? Such as: **OS** - Ubuntu/CentOS **CPU driver** - intel_cpuacpi / intel_pstat **Governor** - performance/powersave/... **EPB** - performance/normal/... **Intel_uncore_frequency driver** - enable/disable
> 
> Hope you guys can provide some suggestions?

We should add some prerequisites or BKM for the nri-balloon policy.

**Comment by changzhi1990** [comment]
We can run the nri-balloon policy out of the container directly:
```
sudo sh -c "NODE_NAME=$(hostname) ./build/bin/nri-resource-policy-balloons --fallback-config  ./build/bin/fallback.cfg --kubeconfig /home/ubuntu/.kube/config --metrics-interval 2s"
```

But the CPU frequency is not adjusted. After some investigation, I found that the CPU controller doesn't start. I added some debug code like this:

![image](https://github.com/containers/nri-plugins/assets/12726668/117d8857-a14f-4908-a1b6-190ae4163226)

The "getCPUController().started" is false. Further, I added some debug code like this:
![image](https://github.com/containers/nri-plugins/assets/12726668/2ef074ed-3a97-4869-9542-779cb03cb08d)

The debug info didn't appear in my terminal. Therefore, I suppose that the CPU controller didn't start yet. 

Hope this can help to debug.

**Comment by klihub** [comment]
@changzi1990 Yes, the original controllers are not hooked into the infra ATM at all. We'll take a look at fixing that.

**Comment by klihub** [comment]
@changzhi1990 This should be now fixed in the 0.1.0-tagged first release and also in the latest main/HEAD. Please take it for a spin.

**Comment by changzhi1990** [comment]
Hi @klihub , thanks for your reply. I have tried the 0.1.0-tagged and I encounter some problems with the doc. In addition, I have fixed them here https://github.com/containers/nri-plugins/pull/88.

After deploying the balloons policy successfully, the CPU frequency still can't be adjusted. Here is the detailed info:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

images:
- name: '*'
  newName: ghcr.io/containers/nri-plugins/nri-resource-policy-balloons
  newTag: unstable

resources:
- ../../base/crds
- ../../base/nri-resource-policy
- sample-configmap.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: nri-resource-policy-balloons
    target:
      group: apps
      version: v1
      kind: DaemonSet
      labelSelector: "app=nri-resource-policy"
    options:
      allowNameChange: true
```
sample-configmap.yaml
```
apiVersion: v1
data:
  policy: |+
    Active: balloons
    ReservedResources:
      CPU: 888m
    balloons:
      BalloonTypes:
        - Name: "b0"
          MinCpus: 2
          MaxCPUs: 8
          CPUClass: low
          MinBalloons: 2
  cpu: |+
    classes:
      high:
        minFreq: 30000000
        maxFreq: 30000000
      low:
        minFreq: 10000000
        maxFreq: 10000000
      turbo:
        minFreq: 30000000
        maxFreq: 36000000
  logger: |+
    Debug: resource-manager,cache,policy,resource-control
  instrumentation: |+
    # The balloons policy exports containers running in each balloon,
    # and cpusets of balloons. Accessible in command line:
    # curl --silent http://localhost:8891/metrics
    HTTPEndpoint: :8891
    PrometheusExport: true

kind: ConfigMap
metadata:
  name: nri-resource-policy-config.default
  namespace: kube-system

```

Here is the log of the nri pod.
[log.txt](https://github.com/containers/nri-plugins/files/11901471/log.txt)

In addition, here is the metrics info:
![image](https://github.com/containers/nri-plugins/assets/12726668/51e2b88e-8e61-455f-a09d-fac9321cbf6f)

The CPU frequency still doesn't adjust:
![image](https://github.com/containers/nri-plugins/assets/12726668/0b69e685-c80e-4741-99e4-0914fc1195db)

**Comment by changzhi1990** [comment]
@jukkar please take a look at this log 
[debug_log.txt](https://github.com/containers/nri-plugins/files/11902605/debug_log.txt)

**Comment by askervin** [comment]
Hi @changzhi1990,

I tried this by building latest nri-plugins (commit 66846cb397314376bc8269ce0549387c89bcc595) and latest containerd in release/1.7 branch (commit 6d148fb319755c7787dfc8eca56d6b5ff4fce9b2).

I applied your config map, though added `,cpu` to the end of the `Debug: ...` line. You might wish to add this to your fallback configuration and configmap in order to get log.Debug() messages from the cpu controller.

I deployed the balloons plugin so that it's launched with following command line arguments:
```
      containers:
        - name: nri-resource-policy-balloons
          args:
            - --host-root
            - /host
            - --fallback-config
            - /etc/nri-resource-policy/nri-resource-policy.cfg
            - --pid-file
            - /tmp/nri-resource-policy.pid
            - -metrics-interval
            - 5s
            - --enable-test-apis
          ...
          volumeMounts:
          - name: hostsysfs
            mountPath: /host/sys
         ...
      volumes:
      ...
      - name: hostsysfs
        hostPath:
          path: /sys
          type: Directory
```

(--host-root and --fallback-config are important for this)

Then I...
1. created a pod into balloon b0
2. modified frequencies of the high CPU class (from 30000000 to 20000000) in the config map
3. kubectl applied new config map
4.. observed following lines in the plugin output:

```
# kubectl logs -n kube-system nri-resource-policy-jqfrr
...
I0707 12:09:01.982074       1 cpu.go:141] enforcing cpu frequency limits {20000000, 20000000} from class "high" on [2 3 4 5]
E0707 12:09:01.982116       1 cpu.go:261] cpufreq enforcement on re-configure failed: Cannot set min freq 20000000: open /host/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq: no such file or directory
```

I was running this trial in a nri-plugin e2e virtual machine, so this was an expected error message as there is no cpufreq in the guest os (directory /host/sys/devices/system/cpu/cpu2/cpufreq is missing). But this at least showed that at least some of expected CPU frequency updates are in place. (`strace -e trace=openat -f -p $(pidof nri-resource-policy-balloons)` showed that the policy indeed tried to open this file for writing).

I'll do more thorough analysis next week in order to see that all expected CPU frequency updates take place.

**Comment by daisy-ycguo** [comment]
Hi, any progress with this issue? 
@askervin

**Comment by marquiz** [comment]
@daisy-ycguo this should now be fixed, in [v0.1.0](https://github.com/containers/nri-plugins/releases/tag/v0.1.0) release. Could you report back if it works as expected?

**Comment by changzhi1990** [comment]
Hi, I have no enough time to test it currently, I will test it as soon as possible.

> @daisy-ycguo this should now be fixed, in [v0.1.0](https://github.com/containers/nri-plugins/releases/tag/v0.1.0) release. Could you report back if it works as expected?

**Comment by changzhi1990** [comment]
As discussed with @askervin, the balloon policy can adjust the CPU frequency in the v0.1.0 version. Meanwhile, we find another issue at https://github.com/containers/nri-plugins/issues/99. And close the current issue. Thanks all!
